[pytest]
import_mode = importlib
addopts = -q
cache_dir=24_meta_orchestration/triggers/ci/pytest_cage/.pytest_cache
python_files = test_*.py
testpaths =
    11_test_simulation/tests/unit
    12_tooling/tests/autorunners
markers =
    testnet: marks tests requiring testnet ENV vars (deselect with '-m "not testnet"')
    slow: marks slow tests (deselect with '-m "not slow"')
