[pytest]
addopts = -q
python_files = test_*.py
testpaths =
    11_test_simulation
markers =
    testnet: marks tests requiring testnet ENV vars (deselect with '-m "not testnet"')
    slow: marks slow tests (deselect with '-m "not slow"')
