"""
SSID Incident Report Generator — structured Markdown output.

Generates a deterministic, auditable incident report from an Incident
and its recovery phases.  stdlib-only.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import UTC, datetime

from .incident_classifier import Incident


def generate_report(
    incident: Incident,
    phases: Sequence[str] | None = None,
) -> str:
    """Return a structured Markdown report for the given incident.

    Parameters
    ----------
    incident : Incident
        The classified (and optionally recovered) incident.
    phases : list[str], optional
        Names of completed recovery phases, e.g.
        ["containment", "diagnose", "repair", "verify"].
    """
    phases = phases or []
    now = datetime.now(UTC).isoformat()

    status = "RECOVERED" if incident.verified else "OPEN"

    lines = [
        f"# Incident Report — {incident.sev_label}",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Incident ID | `{incident.incident_id}` |",
        f"| Type | `{incident.incident_type}` |",
        f"| Severity | **{incident.sev_label}** |",
        f"| Reported severity | `{incident.reported_severity}` |",
        f"| Timestamp | `{incident.timestamp}` |",
        f"| Status | **{status}** |",
        f"| Report generated | `{now}` |",
        "",
        "## Recovery Phases",
        "",
    ]

    if not phases:
        lines.append("_No recovery phases executed._")
    else:
        for i, phase in enumerate(phases, 1):
            lines.append(f"{i}. **{phase}**")

    lines += [
        "",
        "## Containment",
        "",
        f"Status: `{incident.containment_status}`",
        "",
        "## Diagnosis",
        "",
        f"{incident.diagnosis or '_pending_'}",
        "",
        "## Repair",
        "",
        f"{incident.repair_action or '_pending_'}",
        "",
        "## Verification",
        "",
        f"Verified: `{incident.verified}`",
        "",
        "---",
        "_Generated by SSID Incident Recovery System_",
        "",
    ]

    return "\n".join(lines)
