#!/usr/bin/env python3
"""Central registry index generator for 24_meta_orchestration/registry/.

Scans the registry directory for all .yaml and .json files, computes
SHA256 hashes, and writes/updates registry.yaml as the central manifest.
"""

from __future__ import annotations

import hashlib
import sys
from datetime import UTC, datetime
from pathlib import Path

import yaml

REGISTRY_DIR = Path(__file__).resolve().parent
OUTPUT_FILE = REGISTRY_DIR / "registry.yaml"
SCHEMA_VERSION = "1.0.0"

# Directories and files to exclude from the index
EXCLUDE_DIRS = {"generated", "intake", "locks", "logs", "manifests", "tasks", "anchors", "__pycache__"}
EXCLUDE_FILES = {"registry.yaml", "update_registry.py", "update_registry_config.yaml"}


def sha256_of(path: Path) -> str:
    """Compute SHA256 hex digest of a file."""
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def purpose_for(filename: str) -> str:
    """Derive a short purpose description from the filename."""
    stem = Path(filename).stem
    parts = stem.replace("_", " ").replace("-", " ")
    return f"{parts} registry"


def scan_registry_files(registry_dir: Path) -> list[dict]:
    """Scan for .yaml and .json files in the registry directory (non-recursive for excluded dirs)."""
    entries = []
    for p in sorted(registry_dir.iterdir()):
        if p.is_dir():
            if p.name in EXCLUDE_DIRS:
                continue
            # Skip subdirectories — flat scan only
            continue
        if p.name in EXCLUDE_FILES:
            continue
        if p.suffix not in (".yaml", ".json", ".jsonl"):
            continue
        entries.append(
            {
                "file": p.name,
                "path": f"24_meta_orchestration/registry/{p.name}",
                "format": p.suffix.lstrip("."),
                "sha256": sha256_of(p),
                "purpose": purpose_for(p.name),
            }
        )
    return entries


def generate_registry(registry_dir: Path) -> dict:
    """Generate the central registry manifest."""
    files = scan_registry_files(registry_dir)
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_at_utc": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "description": (
            "Central manifest indexing all registry files in "
            "24_meta_orchestration/registry/. Auto-generated by update_registry.py."
        ),
        "file_count": len(files),
        "files": files,
    }


def main() -> int:
    """Entry point."""
    registry_dir = REGISTRY_DIR

    manifest = generate_registry(registry_dir)

    yaml_content = yaml.dump(manifest, default_flow_style=False, sort_keys=False, allow_unicode=True)
    OUTPUT_FILE.write_text(yaml_content, encoding="utf-8")

    print(f"Registry manifest written to: {OUTPUT_FILE}")
    print(f"Total files indexed: {manifest['file_count']}")
    print()
    print("SHA256 Summary:")
    for entry in manifest["files"]:
        print(f"  {entry['sha256'][:16]}...  {entry['file']}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
