"""Smoke test for root 05_documentation.

Auto-generated by level3_scaffold.py — validates basic root structure.
"""

from pathlib import Path

import pytest

ROOT_DIR = Path(__file__).resolve().parent.parent
ROOT_NAME = "05_documentation"


class TestRootStructure:
    """Verify 05_documentation has required L3 artifacts."""

    def test_root_directory_exists(self) -> None:
        assert ROOT_DIR.exists(), f"Root directory {ROOT_DIR} must exist"

    def test_has_readme(self) -> None:
        readme = ROOT_DIR / "README.md"
        assert readme.exists(), f"{ROOT_NAME} must have README.md"

    def test_has_module_yaml(self) -> None:
        module = ROOT_DIR / "module.yaml"
        if module.exists():
            import yaml
            data = yaml.safe_load(module.read_text(encoding="utf-8"))
            assert "name" in data, "module.yaml must have 'name' field"

    def test_has_docs_directory(self) -> None:
        docs = ROOT_DIR / "docs"
        assert docs.exists(), f"{ROOT_NAME} must have docs/ directory"

    def test_has_architecture_doc(self) -> None:
        arch = ROOT_DIR / "docs" / "ARCHITECTURE.md"
        assert arch.exists(), f"{ROOT_NAME} must have docs/ARCHITECTURE.md"
        content = arch.read_text(encoding="utf-8")
        assert len(content) > 50, "ARCHITECTURE.md must not be empty"

    def test_no_secrets_in_root(self) -> None:
        """Scan for common secret patterns."""
        secret_patterns = [
            "AKIA",           # AWS access key
            "ghp_",           # GitHub PAT
            "sk-",            # OpenAI/Stripe key
            "PRIVATE KEY",    # PEM private key
        ]
        for f in ROOT_DIR.rglob("*"):
            if not f.is_file() or f.suffix in {".pyc", ".whl", ".tar", ".gz", ".zip"}:
                continue
            try:
                content = f.read_text(encoding="utf-8", errors="ignore")
                for pattern in secret_patterns:
                    assert pattern not in content, (
                        f"Potential secret pattern '{pattern}' found in {f.relative_to(ROOT_DIR)}"
                    )
            except (OSError, UnicodeDecodeError):
                continue
